# Task-2

## 1-Task

In [323]:
import pandas as pd

In [324]:
sales_full_data=pd.concat(objs= [sales_data_2017,sales_data_2018,sales_data_2019])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,31/03/2019,Sal:9610,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaN,Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaN,Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [325]:
sales_full_data["Date"]=pd.to_datetime(sales_full_data["Date"],errors="coerce")
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,2017-01-04,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,2017-01-04,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,2017-01-04,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,2017-01-04,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,NaT,Sal:9610,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaT,Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaT,Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [326]:
sales_full_data["Date"].dtypes

dtype('<M8[ns]')

In [327]:
sales_full_data.dtypes

Date              datetime64[ns]
Voucher                   object
Party                     object
Product                   object
Qty                       object
Rate                      object
Gross                     object
Disc                      object
Voucher Amount            object
dtype: object

In [328]:
sales_full_data["Voucher"]=pd.to_numeric(sales_full_data["Voucher"],errors="coerce")
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,NaN,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,2017-01-04,NaN,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,2017-01-04,NaN,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,2017-01-04,NaN,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,2017-01-04,NaN,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,NaT,NaN,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaT,NaN,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaT,NaN,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [329]:
sales_full_data["Qty"]=pd.to_numeric(sales_full_data["Qty"],errors="coerce")
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-01-04,NaN,SOLANKI PLASTICS,DONA-VAI-9100,2.0,"1,690.00","3,380.00",NaN,"13,100.00"
1,2017-01-04,NaN,SOLANKI PLASTICS,LITE FOAM(1200),6.0,"1,620.00","9,720.00",NaN,NaN
2,2017-01-04,NaN,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23,"11,500.00",NaN,"30,990.00"
3,2017-01-04,NaN,SARNESWARA TRADERS,LITE FOAM(1200),6.0,"1,620.00","9,720.00",NaN,NaN
4,2017-01-04,NaN,SARNESWARA TRADERS,DONA-VAI-9100,5.0,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,NaT,NaN,HAMPI FOODS,SPOON SOOFY,200.0,40,"8,000.00",NaN,NaN
44736,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaT,NaN,NaN,NaN,NaN,"1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaT,NaN,NaN,NaN,NaN,"10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [330]:
del sales_full_data["Gross"]
sales_full_data
del sales_full_data["Disc"]
sales_full_data
del sales_full_data["Voucher Amount"]
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,NaN,SOLANKI PLASTICS,DONA-VAI-9100,2.0,"1,690.00"
1,2017-01-04,NaN,SOLANKI PLASTICS,LITE FOAM(1200),6.0,"1,620.00"
2,2017-01-04,NaN,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23
3,2017-01-04,NaN,SARNESWARA TRADERS,LITE FOAM(1200),6.0,"1,620.00"
4,2017-01-04,NaN,SARNESWARA TRADERS,DONA-VAI-9100,5.0,"1,690.00"
...,...,...,...,...,...,...
44735,NaT,NaN,HAMPI FOODS,SPOON SOOFY,200.0,40
44736,NaT,NaN,NaN,NaN,NaN,NaN
44737,NaT,NaN,NaN,NaN,NaN,NaN
44738,NaT,NaN,NaN,NaN,NaN,"1,067,808.80"
44739,NaT,NaN,NaN,NaN,NaN,"10,024,197.00"

In [331]:
sales_full_data.drop_duplicates()

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,NaN,SOLANKI PLASTICS,DONA-VAI-9100,2.0,"1,690.00"
1,2017-01-04,NaN,SOLANKI PLASTICS,LITE FOAM(1200),6.0,"1,620.00"
2,2017-01-04,NaN,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23
3,2017-01-04,NaN,SARNESWARA TRADERS,LITE FOAM(1200),6.0,"1,620.00"
4,2017-01-04,NaN,SARNESWARA TRADERS,DONA-VAI-9100,5.0,"1,690.00"
...,...,...,...,...,...,...
44709,NaT,NaN,RR CHIKEN CENTER-MT,ZEND-PREMIUM,4.0,70
44719,NaT,NaN,HOTEL SMART CITY PA,TISSUE ROLLS,50.0,25
44732,NaT,NaN,HAMPI FOODS,LIDS-250ML,NaN,1
44738,NaT,NaN,NaN,NaN,NaN,"1,067,808.80"
44739,NaT,NaN,NaN,NaN,NaN,"10,024,197.00"

In [332]:
sales_full_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 111206 entries, 0 to 44739
Data columns (total 6 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Date     37518 non-null   datetime64[ns]
 1   Voucher  0 non-null       float64
 2   Party    111166 non-null  object
 3   Product  98615 non-null   object
 4   Qty      92196 non-null   float64
 5   Rate     98648 non-null   object
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 5.9+ MB

In [333]:
sales_full_data.isnull().sum()

Date        73688
Voucher    111206
Party          40
Product     12591
Qty         19010
Rate        12558
dtype: int64

In [334]:
sales_full_data.dtypes

Date       datetime64[ns]
Voucher           float64
Party              object
Product            object
Qty               float64
Rate               object
dtype: object

In [335]:
sales_full_data.isna().sum()

Date        73688
Voucher    111206
Party          40
Product     12591
Qty         19010
Rate        12558
dtype: int64

In [336]:
sales_full_data["Date"]=pd.to_datetime(sales_full_data["Date"],errors="coerce")
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,NaN,SOLANKI PLASTICS,DONA-VAI-9100,2.0,"1,690.00"
1,2017-01-04,NaN,SOLANKI PLASTICS,LITE FOAM(1200),6.0,"1,620.00"
2,2017-01-04,NaN,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23
3,2017-01-04,NaN,SARNESWARA TRADERS,LITE FOAM(1200),6.0,"1,620.00"
4,2017-01-04,NaN,SARNESWARA TRADERS,DONA-VAI-9100,5.0,"1,690.00"
...,...,...,...,...,...,...
44735,NaT,NaN,HAMPI FOODS,SPOON SOOFY,200.0,40
44736,NaT,NaN,NaN,NaN,NaN,NaN
44737,NaT,NaN,NaN,NaN,NaN,NaN
44738,NaT,NaN,NaN,NaN,NaN,"1,067,808.80"
44739,NaT,NaN,NaN,NaN,NaN,"10,024,197.00"

In [337]:
sales_full_data.dtypes

Date       datetime64[ns]
Voucher           float64
Party              object
Product            object
Qty               float64
Rate               object
dtype: object

In [338]:
sales_full_data["Voucher"]=pd.to_numeric(sales_full_data["Voucher"],errors="coerce")
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,NaN,SOLANKI PLASTICS,DONA-VAI-9100,2.0,"1,690.00"
1,2017-01-04,NaN,SOLANKI PLASTICS,LITE FOAM(1200),6.0,"1,620.00"
2,2017-01-04,NaN,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23
3,2017-01-04,NaN,SARNESWARA TRADERS,LITE FOAM(1200),6.0,"1,620.00"
4,2017-01-04,NaN,SARNESWARA TRADERS,DONA-VAI-9100,5.0,"1,690.00"
...,...,...,...,...,...,...
44735,NaT,NaN,HAMPI FOODS,SPOON SOOFY,200.0,40
44736,NaT,NaN,NaN,NaN,NaN,NaN
44737,NaT,NaN,NaN,NaN,NaN,NaN
44738,NaT,NaN,NaN,NaN,NaN,"1,067,808.80"
44739,NaT,NaN,NaN,NaN,NaN,"10,024,197.00"

In [339]:
sales_full_data["Voucher"]=(sales_full_data["Voucher"].fillna(1).astype("int64"))
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,"1,690.00"
1,2017-01-04,1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,"1,620.00"
2,2017-01-04,1,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23
3,2017-01-04,1,SARNESWARA TRADERS,LITE FOAM(1200),6.0,"1,620.00"
4,2017-01-04,1,SARNESWARA TRADERS,DONA-VAI-9100,5.0,"1,690.00"
...,...,...,...,...,...,...
44735,NaT,1,HAMPI FOODS,SPOON SOOFY,200.0,40
44736,NaT,1,NaN,NaN,NaN,NaN
44737,NaT,1,NaN,NaN,NaN,NaN
44738,NaT,1,NaN,NaN,NaN,"1,067,808.80"
44739,NaT,1,NaN,NaN,NaN,"10,024,197.00"

In [340]:
sales_full_data["Qty"]=pd.to_numeric(sales_full_data["Qty"],errors="coerce")
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,"1,690.00"
1,2017-01-04,1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,"1,620.00"
2,2017-01-04,1,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23
3,2017-01-04,1,SARNESWARA TRADERS,LITE FOAM(1200),6.0,"1,620.00"
4,2017-01-04,1,SARNESWARA TRADERS,DONA-VAI-9100,5.0,"1,690.00"
...,...,...,...,...,...,...
44735,NaT,1,HAMPI FOODS,SPOON SOOFY,200.0,40
44736,NaT,1,NaN,NaN,NaN,NaN
44737,NaT,1,NaN,NaN,NaN,NaN
44738,NaT,1,NaN,NaN,NaN,"1,067,808.80"
44739,NaT,1,NaN,NaN,NaN,"10,024,197.00"

In [341]:
sales_full_data["Qty"]=(sales_full_data["Qty"].fillna(1).astype("int64"))
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00"
1,2017-01-04,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00"
2,2017-01-04,1,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23
3,2017-01-04,1,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00"
4,2017-01-04,1,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00"
...,...,...,...,...,...,...
44735,NaT,1,HAMPI FOODS,SPOON SOOFY,200,40
44736,NaT,1,NaN,NaN,1,NaN
44737,NaT,1,NaN,NaN,1,NaN
44738,NaT,1,NaN,NaN,1,"1,067,808.80"
44739,NaT,1,NaN,NaN,1,"10,024,197.00"

In [344]:
sales_full_data["Rate"]=sales_full_data["Rate"].fillna(0)
sales_full_data

            Date  Voucher               Party            Product  Qty  Rate
0     2017-01-04        1    SOLANKI PLASTICS      DONA-VAI-9100    2   0.0
1     2017-01-04        1    SOLANKI PLASTICS    LITE FOAM(1200)    6   0.0
2     2017-01-04        1  SARNESWARA TRADERS  VISHNU CHOTA WINE  500  23.0
3     2017-01-04        1  SARNESWARA TRADERS    LITE FOAM(1200)    6   0.0
4     2017-01-04        1  SARNESWARA TRADERS      DONA-VAI-9100    5   0.0
...          ...      ...                 ...                ...  ...   ...
44735        NaT        1         HAMPI FOODS        SPOON SOOFY  200  40.0
44736        NaT        1                 NaN                NaN    1   0.0
44737        NaT        1                 NaN                NaN    1   0.0
44738        NaT        1                 NaN                NaN    1   0.0
44739        NaT        1                 NaN                NaN    1   0.0

[111206 rows x 6 columns]

In [348]:
sales_full_data["Date"]=sales_full_data["Date"].fillna(0)
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04 00:00:00,1,SOLANKI PLASTICS,DONA-VAI-9100,2,0.0
1,2017-01-04 00:00:00,1,SOLANKI PLASTICS,LITE FOAM(1200),6,0.0
2,2017-01-04 00:00:00,1,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,2017-01-04 00:00:00,1,SARNESWARA TRADERS,LITE FOAM(1200),6,0.0
4,2017-01-04 00:00:00,1,SARNESWARA TRADERS,DONA-VAI-9100,5,0.0
...,...,...,...,...,...,...
44735,0,1,HAMPI FOODS,SPOON SOOFY,200,40.0
44736,0,1,NaN,NaN,1,0.0
44737,0,1,NaN,NaN,1,0.0
44738,0,1,NaN,NaN,1,0.0
44739,0,1,NaN,NaN,1,0.0

In [349]:
sales_full_data["Party"]=sales_full_data["Party"].fillna(0)
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04 00:00:00,1,SOLANKI PLASTICS,DONA-VAI-9100,2,0.0
1,2017-01-04 00:00:00,1,SOLANKI PLASTICS,LITE FOAM(1200),6,0.0
2,2017-01-04 00:00:00,1,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,2017-01-04 00:00:00,1,SARNESWARA TRADERS,LITE FOAM(1200),6,0.0
4,2017-01-04 00:00:00,1,SARNESWARA TRADERS,DONA-VAI-9100,5,0.0
...,...,...,...,...,...,...
44735,0,1,HAMPI FOODS,SPOON SOOFY,200,40.0
44736,0,1,0,NaN,1,0.0
44737,0,1,0,NaN,1,0.0
44738,0,1,0,NaN,1,0.0
44739,0,1,0,NaN,1,0.0

In [350]:
sales_full_data["Product"]=sales_full_data["Product"].fillna(0)
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-01-04 00:00:00,1,SOLANKI PLASTICS,DONA-VAI-9100,2,0.0
1,2017-01-04 00:00:00,1,SOLANKI PLASTICS,LITE FOAM(1200),6,0.0
2,2017-01-04 00:00:00,1,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,2017-01-04 00:00:00,1,SARNESWARA TRADERS,LITE FOAM(1200),6,0.0
4,2017-01-04 00:00:00,1,SARNESWARA TRADERS,DONA-VAI-9100,5,0.0
...,...,...,...,...,...,...
44735,0,1,HAMPI FOODS,SPOON SOOFY,200,40.0
44736,0,1,0,0,1,0.0
44737,0,1,0,0,1,0.0
44738,0,1,0,0,1,0.0
44739,0,1,0,0,1,0.0

In [351]:
sales_full_data.isnull().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
dtype: int64

In [352]:
sales_full_data.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

In [353]:
sales_full_data["Date"]=pd.to_datetime(sales_full_data["Date"],errors="coerce")
sales_full_data

            Date  Voucher               Party            Product  Qty  Rate
0     2017-01-04        1    SOLANKI PLASTICS      DONA-VAI-9100    2   0.0
1     2017-01-04        1    SOLANKI PLASTICS    LITE FOAM(1200)    6   0.0
2     2017-01-04        1  SARNESWARA TRADERS  VISHNU CHOTA WINE  500  23.0
3     2017-01-04        1  SARNESWARA TRADERS    LITE FOAM(1200)    6   0.0
4     2017-01-04        1  SARNESWARA TRADERS      DONA-VAI-9100    5   0.0
...          ...      ...                 ...                ...  ...   ...
44735 1970-01-01        1         HAMPI FOODS        SPOON SOOFY  200  40.0
44736 1970-01-01        1                   0                  0    1   0.0
44737 1970-01-01        1                   0                  0    1   0.0
44738 1970-01-01        1                   0                  0    1   0.0
44739 1970-01-01        1                   0                  0    1   0.0

[111206 rows x 6 columns]

In [354]:
sales_full_data.dtypes

Date       datetime64[ns]
Voucher             int64
Party              object
Product            object
Qty                 int64
Rate              float64
dtype: object

In [169]:
sales_full_data.describe()

                                Date           Qty
count                          37518  92196.000000
mean   2018-06-06 01:29:18.835759104    107.032816
min              2017-01-04 00:00:00      0.000000
25%              2017-09-12 00:00:00     10.000000
50%              2018-06-06 00:00:00     48.000000
75%              2019-02-03 00:00:00    120.000000
max              2019-12-09 00:00:00    980.000000
std                              NaN    152.672030

In [18]:
sales_data_2017=pd.read_csv("Sales_transaction_2017.csv")
sales_data_2018=pd.read_csv("Sales_transaction_2018.csv")
sales_data_2019=pd.read_csv("Sales_transaction_2019.csv")
sales_data_2017
sales_data_2018
sales_data_2019

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2018,Sal:146,TP13,SILVER POUCH 9*12,50,85,"4,250.00",NaN,"66,724.00"
1,1/4/2018,Sal:146,TP13,RUBBER,5,290,"1,450.00",NaN,NaN
2,1/4/2018,Sal:146,TP13,DURGA 10*12 Blue,"1,600.00",5.5,"8,800.00",NaN,NaN
3,1/4/2018,Sal:146,TP13,DURGA 13*16 BLUE,400,11,"4,400.00",NaN,NaN
4,1/4/2018,Sal:146,TP13,10*12 SARAS-NAT,600,8.1,"4,860.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,31/03/2019,Sal:9610,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaN,Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaN,Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [336]:
sales_edited_data=pd.read_csv("Sales_transaction_Edited.csv")
sales_edited_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [337]:
sales_edited_data.isnull().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       1
dtype: int64

In [338]:
sales_full_data.isna().sum()

np.int64(0)

In [339]:
sales_edited_data.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

## Task-2

### Merge-left join,right join,inner join,outer join

#### 1.inner_join

In [30]:
sales_edited_data=pd.merge(sales_data_2017,sales_data_2018,on=["Party","Product"],how="inner",sort=False)
sales_edited_data

,Date_x,Voucher_x,Party,Product,Qty_x,Rate_x,Gross_x,Disc_x,Voucher Amount_x,Date_y,Voucher_y,Qty_y,Rate_y,Gross_y,Disc_y,Voucher Amount_y
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00",28/05/2019,Sal:1533,7,"1,640.00","11,480.00",NaN,"19,580.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00",10/6/2019,Sal:1873,5,"1,640.00","8,200.00",NaN,NaN
2,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00",15/07/2019,Sal:2795,3,"1,640.00","4,920.00",NaN,NaN
3,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00",18/07/2019,Sal:2716,1,"1,640.00","1,640.00",NaN,"1,640.00"
4,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00",18/07/2019,Sal:2796,3,"1,640.00","4,920.00",NaN,"4,920.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444833,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,"274,408.60","674,780.19","7,168,515.80","69,050.00","7,119,450.80"
444834,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,NaN,NaN,NaN,NaN,NaN
444835,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,NaN,NaN,NaN,NaN,NaN
444836,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
444837,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

#### 2.outer_join

In [31]:
sales_edited_data=pd.merge(sales_data_2017,sales_data_2018,on=["Party","Product"],how="outer",sort=False)
sales_edited_data

,Date_x,Voucher_x,Party,Product,Qty_x,Rate_x,Gross_x,Disc_x,Voucher Amount_x,Date_y,Voucher_y,Qty_y,Rate_y,Gross_y,Disc_y,Voucher Amount_y
0,NaN,NaN,AND BAKERY,,NaN,NaN,NaN,NaN,NaN,,,,,,,
1,NaN,NaN,BANK),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,BANK),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,BANK),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,BANK),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473063,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,"274,408.60","674,780.19","7,168,515.80","69,050.00","7,119,450.80"
473064,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,NaN,NaN,NaN,NaN,NaN
473065,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,NaN,NaN,NaN,NaN,NaN
473066,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
473067,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

#### 3.left_join

In [32]:
sales_edited_data=pd.merge(sales_data_2017,sales_data_2018,on=["Party","Product"],how="left",sort=False)
sales_edited_data

,Date_x,Voucher_x,Party,Product,Qty_x,Rate_x,Gross_x,Disc_x,Voucher Amount_x,Date_y,Voucher_y,Qty_y,Rate_y,Gross_y,Disc_y,Voucher Amount_y
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00",28/05/2019,Sal:1533,7,"1,640.00","11,480.00",NaN,"19,580.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00",10/6/2019,Sal:1873,5,"1,640.00","8,200.00",NaN,NaN
2,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00",15/07/2019,Sal:2795,3,"1,640.00","4,920.00",NaN,NaN
3,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00",18/07/2019,Sal:2716,1,"1,640.00","1,640.00",NaN,"1,640.00"
4,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00",18/07/2019,Sal:2796,3,"1,640.00","4,920.00",NaN,"4,920.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465172,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,"274,408.60","674,780.19","7,168,515.80","69,050.00","7,119,450.80"
465173,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,NaN,NaN,NaN,NaN,NaN
465174,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,NaN,NaN,NaN,NaN,NaN
465175,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
465176,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

#### 4. right_join

In [33]:
sales_edited_data=pd.merge(sales_data_2017,sales_data_2018,on=["Party","Product"],how="right",sort=False)
sales_edited_data

,Date_x,Voucher_x,Party,Product,Qty_x,Rate_x,Gross_x,Disc_x,Voucher Amount_x,Date_y,Voucher_y,Qty_y,Rate_y,Gross_y,Disc_y,Voucher Amount_y
0,3/4/2017,Sal:18,BALAJI PLASTICS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN,1/4/2019,Sal:687,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,9/4/2017,Sal:423,BALAJI PLASTICS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN,1/4/2019,Sal:687,1,"1,730.00","1,730.00",NaN,"3,460.00"
2,14/04/2017,Sal:342,BALAJI PLASTICS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN,1/4/2019,Sal:687,1,"1,730.00","1,730.00",NaN,"3,460.00"
3,19/04/2017,Sal:567,BALAJI PLASTICS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,"23,285.00",1/4/2019,Sal:687,1,"1,730.00","1,730.00",NaN,"3,460.00"
4,28/04/2017,Sal:824,BALAJI PLASTICS,DONA-VAI-9100,7,"1,690.00","11,830.00",NaN,"24,250.00",1/4/2019,Sal:687,1,"1,730.00","1,730.00",NaN,"3,460.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452724,NaN,Total,NaN,NaN,"480,806.30","461,266.00","7,572,732.76","51,040.00","7,538,183.76",NaN,Total,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"
452725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"
452726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"
452727,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13",NaN,Total,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"
452728,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

#### 5.left_on and_right_on 1.inner - left_on & right_on

In [34]:
sales_edited_data=pd.merge(sales_data_2017,sales_data_2018,left_on="Party",right_on="Product",how="inner",sort=False)
sales_edited_data

,Date_x,Voucher_x,Party_x,Product_x,Qty_x,Rate_x,Gross_x,Disc_x,Voucher Amount_x,Date_y,Voucher_y,Party_y,Product_y,Qty_y,Rate_y,Gross_y,Disc_y,Voucher Amount_y
0,NaN,Total,NaN,NaN,"725,098.20","892,995.90","10,156,375.86","99,183.00","10,079,469.86",NaN,NaN,ASTICS-PDKR,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Total,NaN,NaN,"725,098.20","892,995.90","10,156,375.86","99,183.00","10,079,469.86",NaN,NaN,R,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Total,NaN,NaN,"725,098.20","892,995.90","10,156,375.86","99,183.00","10,079,469.86",NaN,NaN,R,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Total,NaN,NaN,"725,098.20","892,995.90","10,156,375.86","99,183.00","10,079,469.86",NaN,NaN,R,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Total,NaN,NaN,"725,098.20","892,995.90","10,156,375.86","99,183.00","10,079,469.86",NaN,NaN,R,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26845,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,ET,NaN,NaN,NaN,NaN,NaN,NaN
26846,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26847,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26848,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
26849,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

#### 2.outer=left_on & right_on

In [35]:
sales_edited_data=pd.merge(sales_data_2017,sales_data_2018,left_on="Party",right_on="Product",how="outer",sort=False)
sales_edited_data

,Date_x,Voucher_x,Party_x,Product_x,Qty_x,Rate_x,Gross_x,Disc_x,Voucher Amount_x,Date_y,Voucher_y,Party_y,Product_y,Qty_y,Rate_y,Gross_y,Disc_y,Voucher Amount_y
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,28/3,,0,0,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,25/2,,0,0,,,
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,"jamal ,khadervali",,,,,,
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,by hand,,,,,,
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,credit bill,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91506,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,ET,NaN,NaN,NaN,NaN,NaN,NaN
91507,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91508,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91509,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
91510,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

#### 3.left=left_on & right_on

In [36]:
sales_edited_data=pd.merge(sales_data_2017,sales_data_2018,left_on="Party",right_on="Product",how="left",sort=False)
sales_edited_data

,Date_x,Voucher_x,Party_x,Product_x,Qty_x,Rate_x,Gross_x,Disc_x,Voucher Amount_x,Date_y,Voucher_y,Party_y,Product_y,Qty_y,Rate_y,Gross_y,Disc_y,Voucher Amount_y
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74120,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,ET,NaN,NaN,NaN,NaN,NaN,NaN
74121,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74122,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74123,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
74124,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

#### 4.right=left_on & right_on

In [37]:
sales_edited_data=pd.merge(sales_data_2017,sales_data_2018,left_on="Party",right_on="Product",how="right",sort=False)
sales_edited_data

,Date_x,Voucher_x,Party_x,Product_x,Qty_x,Rate_x,Gross_x,Disc_x,Voucher Amount_x,Date_y,Voucher_y,Party_y,Product_y,Qty_y,Rate_y,Gross_y,Disc_y,Voucher Amount_y
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,28/3,,0,0,,,
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44231,NaN,Total,NaN,NaN,"480,806.30","461,266.00","7,572,732.76","51,040.00","7,538,183.76",NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"
44232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"
44233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"
44234,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13",NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"
44235,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71",NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

# Task-3

## List comprehension

In [38]:
insurance_data=pd.read_csv("Insurance.csv")
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

#### 1.Example

In [39]:
insurance_data["Eligible_teenagers"]=["they are teenagers" if age<20 else "Not teenagers" for age in insurance_data["age"]]  
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligible_teenagers
0,19,female,27.900,0,yes,southwest,16884.92400,they are teenagers
1,18,male,33.770,1,no,southeast,1725.55230,they are teenagers
2,28,male,33.000,3,no,southeast,4449.46200,Not teenagers
3,33,male,22.705,0,no,northwest,21984.47061,Not teenagers
4,32,male,28.880,0,no,northwest,3866.85520,Not teenagers
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Not teenagers
1334,18,female,31.920,0,no,northeast,2205.98080,they are teenagers
1335,18,female,36.850,0,no,southeast,1629.83350,they are teenagers
1336,21,female,25.800,0,no,southwest,2007.94500,Not teenagers
1337,61,female,29.070,0,yes,northwest,29141.36030,Not teenagers

#### 2.Example

In [40]:
insurance_data["southwest_regioner"]=["they are southwest" if region not in insurance_data else "not they northeast" for region in insurance_data["region"]] 
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligible_teenagers,southwest_regioner
0,19,female,27.900,0,yes,southwest,16884.92400,they are teenagers,they are southwest
1,18,male,33.770,1,no,southeast,1725.55230,they are teenagers,they are southwest
2,28,male,33.000,3,no,southeast,4449.46200,Not teenagers,they are southwest
3,33,male,22.705,0,no,northwest,21984.47061,Not teenagers,they are southwest
4,32,male,28.880,0,no,northwest,3866.85520,Not teenagers,they are southwest
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Not teenagers,they are southwest
1334,18,female,31.920,0,no,northeast,2205.98080,they are teenagers,they are southwest
1335,18,female,36.850,0,no,southeast,1629.83350,they are teenagers,they are southwest
1336,21,female,25.800,0,no,southwest,2007.94500,Not teenagers,they are southwest
1337,61,female,29.070,0,yes,northwest,29141.36030,Not teenagers,they are southwest

# Task-4

## lambda

In [361]:
from functools import reduce

In [362]:
employee_data=pd.read_csv("employee_data.csv")
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [363]:
employee_data["current values"]=employee_data.apply("Salary").map(lambda x: x * 2).round()
employee_data

      Name   Age Department   Salary   Join_Date  current values
0   Rajesh  29.0        Ops  60000.0  21-05-2023        120000.0
1    Nasir  31.0    IT Tech      NaN  12-11-2020             NaN
2  Mathiew   NaN    Support  58000.0  15-01-2025        116000.0
3  Gilbert  29.0        Ops  60000.0  21-05-2021        120000.0
4    Kevin  28.0    Support  61000.0  30-07-2024        122000.0
5    Navin  35.0    Support  72000.0  19-08-2023        144000.0
6      NaN  40.0         IT  64000.0  10-09-2022        128000.0
7    Nasir  31.0    IT Tech      NaN  12-11-2020             NaN

In [364]:
employee_data["current values"]=employee_data.apply("Salary").filter([lambda x: x * 2]).round()
employee_data

      Name   Age Department   Salary   Join_Date  current values
0   Rajesh  29.0        Ops  60000.0  21-05-2023             NaN
1    Nasir  31.0    IT Tech      NaN  12-11-2020             NaN
2  Mathiew   NaN    Support  58000.0  15-01-2025             NaN
3  Gilbert  29.0        Ops  60000.0  21-05-2021             NaN
4    Kevin  28.0    Support  61000.0  30-07-2024             NaN
5    Navin  35.0    Support  72000.0  19-08-2023             NaN
6      NaN  40.0         IT  64000.0  10-09-2022             NaN
7    Nasir  31.0    IT Tech      NaN  12-11-2020             NaN

In [368]:
employee_data["current values"]= reduce(lambda result,x:result+[round(x*2)],employee_data["Salary"].fillna(0),[])
employee_data

      Name   Age Department   Salary   Join_Date  current values
0   Rajesh  29.0        Ops  60000.0  21-05-2023          120000
1    Nasir  31.0    IT Tech      NaN  12-11-2020               0
2  Mathiew   NaN    Support  58000.0  15-01-2025          116000
3  Gilbert  29.0        Ops  60000.0  21-05-2021          120000
4    Kevin  28.0    Support  61000.0  30-07-2024          122000
5    Navin  35.0    Support  72000.0  19-08-2023          144000
6      NaN  40.0         IT  64000.0  10-09-2022          128000
7    Nasir  31.0    IT Tech      NaN  12-11-2020               0